variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/build'
  
install:
   stage: .pre
   script:
      - npm install

build:
   stage: build
   script:
      - CI=false npm run build

deploy:
  stage: deploy
  image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy
  script:
    - echo "Build and App deployed successfully."
  only:
    - main
