variables:
  API_TOKEN: $DEPLOYMENT_TOKEN
  APP_PATH: '$CI_PROJECT_DIR/src'

image: registry.gitlab.com/static-web-apps/azure-static-web-apps-deploy

install:
   stage: .pre
   script:
      - yarn install

build:
   stage: build
   script:
      - CI=false yarn run build

deploy:
  stage: deploy
  script:
    - echo "Build and App deployed successfully."
  only:
    - main
